export default {
    ADD: {
        RAW_IMAGE_URI: 'ADD_RAW_IMAGE_URI',
        DETECTED_IMAGE_BASE64: 'ADD_DETECTED_IMAGE_BASE64'
    },
    SET: {
        ADDRESS_PORT: 'SET_ADDRESS_PORT',
        URL: 'SET_URL',
        PORT: 'SET_PORT'
    },
    DETECTED_IMAGE: 'DETECTED_IMAGE',
    CHANGE_STATE_IMAGE: 'CHANGE_STATE_IMAGE',
    SHOW_DETECTED_IMAGE: 'SHOW_DETECTED_IMAGE',
    SHOW_RAW_IMAGE: 'SHOW_RAW_IMAGE',
    SHOW_PROCESSING_STATUS: 'SHOW_PROCESSING_STATUS',
    STATUS: {
        RAW_IMAGE: 'RAW_IMAGE',
        DETECTED_IMAGE: 'DETECTED_IMAGE',
        PROCESSING: 'PROCESSING'
    }
}